# static fields are here
'api': '0.13'
'contact':
  'email': 'info@hackerspace-krk.pl'
  'facebook': 'HackerspaceKrakow'
  'ml': 'hackerspace-krk@googlegroups.com'
  'phone': '+48124447567'
  'twitter': '@hackerspace_krk'
#'icon':
#  'closed': false
#  'open': false
'cam': ["http://at.hskrk.pl/static/hardroom.jpeg", "http://at.hskrk.pl/static/softroom.jpeg", "http://at.hskrk.pl/static/korytarz.jpeg", "http://at.hskrk.pl/static/elelab.jpeg"]
'issue_report_channels': ['email']
'location':
  'address': "Zacisze 5/P1, 31-156 Kraków, Poland"
  'lat': 50.066085
  'lon': 19.943359
'logo': 'http://hackerspace-krk.pl/wp-content/themes/hskrk/images/logo.png'
'space': 'Hackerspace KRK'
'state': {'open': null} # filled from whois!
'url': 'http://hackerspace-krk.pl'
'projects':
   - 'https://github.com/HackerspaceKRK/'
